"""create schedule contents

Revision ID: 131caad3fe77
Revises: 61c0803c3082
Create Date: 2026-04-18 22:17:39.999025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131caad3fe77'
down_revision: Union[str, Sequence[str], None] = '61c0803c3082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('contents', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'contents')
    # ### end Alembic commands ###
